language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
  - testem
before_install:
- mkdir phantomjs-2.0.0
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O phantomjs-2.0.0/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xvf phantomjs-2.0.0/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C phantomjs-2.0.0/
- export PATH=$PWD/phantomjs-2.0.0:$PATH
- npm config set spin false
- npm install -g npm@^2
- git clone https://github.com/testem/testem.git || true
- pushd testem && git fetch && git checkout v1.7.1 && npm i && npm link && popd
- npm link testem
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
- script/travis-deploy.sh
after_failure:
  - ls /tmp/*.dmp
  - cat /tmp/*.dmp
